on:
  push:

jobs:
  deploy:
    runs-on: docker
    steps:
      - run: npm i --global vercel
      - name: Pull secrets
        if: ${{ env.GITHUB_REF }} == "refs/main"
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Pull secrets (preview)
        if: ${{ env.GITHUB_REF }} != "refs/main"
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: |
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      