import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import { Container, NavLink } from "theme-ui";
import fs from "fs/promises";
import { docsGetListOfProjects } from "@/lib/docsFsUtils";

export default function DocsIndex({ directories }: { directories: string[] }) {
    return (
        <>
          <Navbar />
          <Container>
                <center>
                    <h1>Welcome!</h1>
                    <p>
                        This is where the autogenerated documentation for all my projects exists
                        <br />
                        The default version of the documentation is built from the latest avaliable commit
                    </p>
                </center>
          </Container>
          <Container>
                <h2>Projects</h2>
                <ul>
                    {directories.map((directory) => {
                        return <li key={directory}><NavLink href={`/docs/${directory}`} key={directory}>{directory}</NavLink></li>
                    }
                    )}
                </ul>
          </Container>
          <Footer />
        </>
    )
}
export async function getStaticProps() {
    const directories = await docsGetListOfProjects();
    return {
        props: {
            directories
        }
    }
}